### ISSUE TITLE
Sample code no longer compiles under Version 2.1.12

### ISSUE THREAD

**Issue by genifycom** [georg-jung/MozJpegSharp#69]
The sample code provided on the code page https://github.com/georg-jung/MozJpegSharp no longer compiles.

This line
var compressed = tjc.Compress(bmp, MozJpegSharp.TJSubsamplingOption.Chrominance420, 75, MozJpegSharp.TJFlags.None);
reports:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1501	No overload for method 'Compress' takes 4 arguments

Can you provide an updated base sample please :)

**Comment by georg-jung** [comment]
Did you install the GdiPlus package in addition?

**Comment by genifycom** [comment]
Got it. Sorry I missed that.
