### ISSUE TITLE
Pixelation when under .netcore linux

### ISSUE THREAD

**Issue by maxenko** [georg-jung/MozJpegSharp#74]
I am running into pixilation issue when using MozJpegSharp from within docker deployment via standard MS template which is Debian.

When running compression from within VS on windows - results are good. However after deploying the same code to Docker, compressing any image appears to cause fairly noticeable pixilation.

I've tried changing parameters, but the results are the same.

Windows:
![test_thumb_win](https://user-images.githubusercontent.com/1999105/140663752-f15e5b1c-105a-4f2e-b4b6-2a92723fdfaf.jpg)

Linux:
![test_thumb_lin](https://user-images.githubusercontent.com/1999105/140663751-f34c24c3-2e1f-4b49-afab-34caa1cefd9a.jpg)

Source file:
![test](https://user-images.githubusercontent.com/1999105/140663746-66a7f48d-23cd-4008-8d99-a4dff636269d.jpg)

Any suggestions appreciated.

Encoding with (F#):

```fsharp
let writeMozJpg (img:System.Drawing.Image) path =
        async {
            use bmp = new System.Drawing.Bitmap(img)
            use tjc = new MozJpegSharp.TJCompressor();
            let compressedBytes = tjc.Compress(bmp, MozJpegSharp.TJSubsamplingOption.Chrominance420, 75, MozJpegSharp.TJFlags.AccurateDct)

            if compressedBytes.Length > 0 then
                use file = File.Create(path)
                do! file.AsyncWrite(compressedBytes,0,compressedBytes.Length)
                file.Close()
                return (true, path)
            else
                return (false, String.Empty)
        }
```

Dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:5.0
EXPOSE 8181

RUN apt update
RUN apt install -y libgdiplus
RUN apt install -y libturbojpeg0

COPY bin/Release/net5.0/publish/ App/
WORKDIR /App
ENTRYPOINT ["dotnet", "matter.App.dll", "appsettings.json"]
```

**Comment by georg-jung** [comment]
Are you sure this is related to MozJpegSharp?

Thoughts:
* You seem to resize the source picture but resizing does not happen in the code you posted here
* The pixelation seems quite related to the resizing
* libgdiplus might not behave 100% same as GDI+ does on windows (I don't know, but I guess, as it is a third party reimplementation)
  * I could imagine that "implemetation details" like "what [this constructor](http://msdn.microsoft.com/en-us/library/0wh0045z.aspx) does internally" etc. differ

What would be helpful to further diagnose your problem
* post more of your code, especially the resizing part
* try saving the resized image using libgdiplus, without using MozJpegSharp and check if pixelation occurs
* try using [MozJpegSharp.SkiaSharp](https://www.nuget.org/packages/MozJpegSharp.SkiaSharp/) instead of MozJpegSharp.GdiPlus. That is probably the better idea for non-windows OSes. See the [README](https://github.com/georg-jung/MozJpegSharp#package-overview).

**Comment by maxenko** [comment]
@georg-jung thank you for quick response, I will investigate further based on your suggestions.

It works perfect under windows, so I am not entirely sure why resizing would affect it. Its likely the linux library like you're saying.

I am using standard .net for resizing:
```fsharp
    let resizeByWidth (img:System.Drawing.Image) w = 
        let _w          = (float)w
        let _ratio      = _w / (float)img.Width
        let _h          = Math.Max( 1.0, (float)img.Height * _ratio)
        (new Bitmap(img, (int)_w, (int)_h)) :> System.Drawing.Image
```

which is called from:
```fsharp
    let saveMozJpgThumb toPath stream resX =
        async {
            use img = Image.FromStream stream
            use resized = resizeByWidth img resX
            return! writeMozJpg resized toPath
        }
```

Looking into other suggestions now, thank you.

**Comment by georg-jung** [comment]
> It works perfect under windows, so I am not entirely sure why resizing would affect it

What I'm saying is that I could imagine that the resizing causes the pixelation on Linux, not saving using MozJpegSharp. Resizing can be done in many different ways. See i.e. [here](https://stackoverflow.com/a/24199315/1200847). Now, the code you posted might see _how/which way resizing is done_ as an implementation detail. And the implementations of GDI+ on Windows and libgdiplus on Linux differ. Hope this helps.

**Comment by maxenko** [comment]
@georg-jung you're correct, this has nothing to do with your library. Apologies for false alarm. I think the defaults are different between implementations.

This works:
```fsharp
    let resizeByWidth (img:System.Drawing.Image) w = 
        let _w          = (float)w
        let _ratio      = _w / (float)img.Width
        let _h          = Math.Max( 1.0, (float)img.Height * _ratio)
        let bmp         = new Bitmap((int)_w, (int)_h)
        use g           = Graphics.FromImage(bmp)
        
        g.InterpolationMode <- InterpolationMode.High

        let rect = new System.Drawing.Rectangle(0, 0, (int)_w, (int)_h)
        g.DrawImage(img, rect);
        bmp
```
